### ISSUE TITLE
Replace Option<T> type with Remora.Rest's Optional<TResult>

### ISSUE THREAD

**Issue by TheBrambleShark** [serdedotnet/serde#109]
The [Optional<TResult>](https://github.com/Remora/Remora.Rest/blob/main/Remora.Rest.Core/Optional.cs) type from Remora.Rest is a more feature-rich implementation of the same principal, and in my opinion comes with better naming. @Nihlus has given his approval for its use in this library in anticipation of Serde being promoted into a .NET feature.

![image](https://user-images.githubusercontent.com/7003081/227592054-b7bd9591-1e22-4a71-85e9-30298fd0791a.png)

Additional features:

- IsDefined() and IsDefined(out TValue)
- Map() methods, allowing the conversion of one optional type into another
- OrDefault() and OrThrow() methods, though the former does in fact live in the Option<T> type
- Plenty of additional analyzers through System.Diagnostics, System.Diagnostics.CodeAnalysis, and Jetbrains.Annotations.
- Equality operators
- GetHashCode() and ToString()

**Comment by agocke** [comment]
So, the one use that Serde directly has for Option is holding the "possibly initialized" fields in deserialization.

I think the eventual goal is going to have to be not using Option at all -- if all we need to know is whether a fixed set of fields is initialized, holding a bit set is going to be a lot faster and more space efficient than using an Option for each field.

**Comment by agocke** [comment]
> @Nihlus has given his approval for its use in this library in anticipation of Serde being promoted into a .NET feature.

I can't promise anything yet! Right now I'm just trying to make sure the approach works for the common use cases.

**Comment by TheBrambleShark** [comment]
> So, the one use that Serde directly has for Option is holding the "possibly initialized" fields in deserialization.
> 
> I think the eventual goal is going to have to be not using Option at all -- if all we need to know is whether a fixed set of fields is initialized, holding a bit set is going to be a lot faster and more space efficient than using an Option for each field.

I've found it particularly useful for use when (de)serializing results from API endpoints, which is what Remora.Rest is responsible for. Sometimes an endpoint simply doesn't provide a value, and in certain situations, "not present", null, and present with a value are three completely different states, so representing a type as nullable doesn't always make the most sense.

I will say that I have found less of a use for it when deserializing json files on disk, so if you think it may be more appropriate for a library like Remora.Rest we can definitely keep it there.

**Comment by TheBrambleShark** [comment]
> > @Nihlus has given his approval for its use in this library in anticipation of Serde being promoted into a .NET feature.
> 
> I can't promise anything yet! Right now I'm just trying to make sure the approach works for the common use cases.

Understood! I do think Serde is a good candidate, but I definitely can't say I'm any sort of expert on (de)serialization. I'll be looking forward to see what you determine.
