### ISSUE TITLE
ImmutableArray<ReferenceType> causes virtual method pointer lookup failure in NativeAOT

### ISSUE THREAD

**Issue by jtschuster** [serdedotnet/serde#93]
Not sure if the issue is with serde-dn or NativeAOT, but I ran into an issue with deserializing ImmutableArray<Workload> in dnvm after I had switched workload it to a reference type. I found making it a struct again fixed the issue so far, and I thought I'd let you know in case you hit something similar.

```
Process terminated. Generic virtual method pointer lookup failure.

Declaring type handle: MethodTable:0x00007FF6470BFF80
Target type handle: MethodTable:0x00007FF64711D7E8
Method name: Serde.IDeserializeVisitor<System.Collections.Immutable.ImmutableArray<T>>.VisitEnumerable
Instantiation:
  Argument 00000000: MethodTable:0x00007FF647113320
```

**Comment by agocke** [comment]
Seems very likely that this is a NativeAOT issue. Serde is just regular C#, so there should be no way this is possible. I'd file a bug on runtime.

**Comment by agocke** [comment]
This is https://github.com/dotnet/runtime/issues/77070. I've implemented some workarounds, but it's likely still possible to hit this.
